project_id = "aalritrcwtocwcjylyfl"

[functions.graph-api]
verify_jwt = false

[functions.agent-respond]
verify_jwt = false

[functions.workflow-api]
verify_jwt = false

[functions.workflow-runner]
verify_jwt = false

[functions.agent-respond-simulation]
verify_jwt = false

[functions.strategy-agent]
verify_jwt = false

[functions.simulation-agent]
verify_jwt = false
