version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: strategic-graph-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/neo4j_password_change_me
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - strategic-graph-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: strategic-graph-backend
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4j_password_change_me
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - strategic-graph-network
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: strategic-graph-frontend
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - strategic-graph-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  strategic-graph-network:
    driver: bridge
